"""Generate PRISMA 2020 flow diagram."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


def load_state(state_file: Path) -> dict:
    """Load review state from JSON file."""
    if not state_file.exists():
        return {}
    with open(state_file, "r", encoding="utf-8") as f:
        return json.load(f)


def save_state(state: dict, state_file: Path) -> None:
    """Save review state to JSON file."""
    state_file.parent.mkdir(parents=True, exist_ok=True)
    with open(state_file, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


def generate_markdown_diagram(state: dict, path: Path) -> None:
    """Generate a markdown text PRISMA flow diagram."""
    path.parent.mkdir(parents=True, exist_ok=True)

    search = state.get("search", {})
    dedup = state.get("dedup", {})
    screen = state.get("screen", {})

    total_found = search.get("total", 0)
    sources = {k: v for k, v in search.items() if k != "total"}
    dups_removed = dedup.get("duplicates_removed", 0)
    after_dedup = dedup.get("remaining", 0)
    included = screen.get("included", 0)
    excluded = screen.get("excluded", 0)
    maybe = screen.get("maybe", 0)

    elig = state.get("eligibility", {})
    elig_input = elig.get("input_from_screening", 0)
    elig_included = elig.get("included", 0)
    elig_excluded = elig.get("excluded", 0)
    elig_remaining = elig.get("remaining", 0)

    source_lines = "\n".join(f"    {name}: n = {count}" for name, count in sources.items())

    md = f"""# PRISMA 2020 Flow Diagram

## Identification

Records identified from databases and registers:
{source_lines}
    **Total records identified: n = {total_found}**

Records removed before screening:
    Duplicate records removed: n = {dups_removed}
    Records marked as ineligible by automation tools (keyword rules): n = {excluded}

## Screening

Records screened (title + abstract): n = {after_dedup}
    Records assessed by keyword rules + AI review: n = {after_dedup}
    Records excluded (keyword rules + AI-assisted): n = {excluded}
    Records remaining for review: n = {maybe}
    Records included after screening: n = {included}
"""

    if elig:
        md += f"""
## Eligibility

Reports sought for retrieval: n = {elig_input}
Reports assessed for eligibility (AI-assisted, stricter criteria): n = {elig_input}
    Reports excluded: n = {elig_excluded}
    Reports remaining to assess: n = {elig_remaining}

## Included

Studies included in review: n = {elig_included}
Reports of included studies: n = {elig_included}
"""
    else:
        md += f"""
## Included

Studies included in review: n = {included}
Reports of included studies: n = {included}
"""

    md += f"""
---

### Automation Tools Used (PRISMA 2020 Item 8)

- **Keyword screening**: Rule-based automation (prisma_tool screen module)
- **AI-assisted screening**: Claude via Model Context Protocol (MCP)
- **Deduplication**: DOI matching + fuzzy title matching (prisma_tool dedup module)
- All decisions logged with method (rule/ai/manual) and reason

*Generated by [prisma_tool](https://github.com) — PRISMA 2020 compliant*
"""

    with open(path, "w", encoding="utf-8") as f:
        f.write(md)


def generate_png_diagram(state: dict, path: Path) -> None:
    """Generate a PRISMA 2020 flow diagram as PNG using matplotlib."""
    path.parent.mkdir(parents=True, exist_ok=True)

    search = state.get("search", {})
    dedup = state.get("dedup", {})
    screen = state.get("screen", {})

    total = search.get("total", 0)
    dups = dedup.get("duplicates_removed", 0)
    after_dedup = dedup.get("remaining", 0)
    included = screen.get("included", 0)
    excluded = screen.get("excluded", 0)
    maybe = screen.get("maybe", 0)

    elig = state.get("eligibility", {})
    has_eligibility = bool(elig)
    elig_input = elig.get("input_from_screening", 0)
    elig_included = elig.get("included", 0)
    elig_excluded = elig.get("excluded", 0)

    # Source breakdown
    sources = {k: v for k, v in search.items() if k != "total"}
    source_text = "\n".join(f"{k}: {v}" for k, v in sources.items())

    fig_h = 13 if has_eligibility else 10
    fig, ax = plt.subplots(1, 1, figsize=(12, fig_h))
    ax.set_xlim(0, 10)
    y_max = 13 if has_eligibility else 10
    ax.set_ylim(0, y_max)
    ax.axis("off")
    ax.set_title("PRISMA 2020 Flow Diagram", fontsize=16, fontweight="bold", pad=20)

    def draw_box(x, y, w, h, text, color="#E8F4FD", border="#2196F3"):
        rect = mpatches.FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.1",
            facecolor=color, edgecolor=border, linewidth=1.5
        )
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
                fontsize=8, wrap=True, fontweight="normal",
                bbox=dict(boxstyle="round,pad=0.05", facecolor="none", edgecolor="none"))

    def draw_arrow(x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                     arrowprops=dict(arrowstyle="->", color="#666666", lw=1.5))

    removal_text = f"Records removed before\nscreening:\nDuplicates (n = {dups})\nAutomation tool\nexclusions (n = {excluded})"

    if has_eligibility:
        # --- Layout with eligibility (4 stages) ---
        # IDENTIFICATION
        ax.text(0.3, 12.5, "IDENTIFICATION", fontsize=10, fontweight="bold", color="#1565C0")
        draw_box(0.5, 11.0, 3.5, 1.2,
                 f"Records identified from\ndatabases & registers\n(n = {total})\n{source_text}",
                 color="#E3F2FD", border="#1565C0")
        draw_box(5.5, 11.0, 3.5, 1.2,
                 removal_text,
                 color="#FFEBEE", border="#C62828")
        draw_arrow(4.0, 11.6, 5.5, 11.6)

        # SCREENING
        ax.text(0.3, 10.3, "SCREENING", fontsize=10, fontweight="bold", color="#F57F17")
        draw_box(0.5, 8.5, 3.5, 1.2,
                 f"Records screened\n(title + abstract)\n(n = {after_dedup})\nIncluded: n = {included}",
                 color="#FFF8E1", border="#F57F17")
        draw_arrow(2.25, 11.0, 2.25, 9.7)
        draw_box(5.5, 8.5, 3.5, 1.2,
                 f"Records excluded\n(keyword rules +\nAI-assisted review)\n(n = {excluded})",
                 color="#FFEBEE", border="#C62828")
        draw_arrow(4.0, 9.1, 5.5, 9.1)

        # ELIGIBILITY
        ax.text(0.3, 7.8, "ELIGIBILITY", fontsize=10, fontweight="bold", color="#6A1B9A")
        draw_box(0.5, 5.8, 3.5, 1.2,
                 f"Reports assessed for\neligibility (AI-assisted)\n(n = {elig_input})",
                 color="#F3E5F5", border="#6A1B9A")
        draw_arrow(2.25, 8.5, 2.25, 7.0)
        draw_box(5.5, 5.8, 3.5, 1.2,
                 f"Reports excluded\n(stricter criteria)\n(n = {elig_excluded})",
                 color="#FFEBEE", border="#C62828")
        draw_arrow(4.0, 6.4, 5.5, 6.4)

        # INCLUDED
        ax.text(0.3, 5.1, "INCLUDED", fontsize=10, fontweight="bold", color="#2E7D32")
        draw_box(0.5, 3.5, 3.5, 1.2,
                 f"Studies included\nin review\n(n = {elig_included})",
                 color="#E8F5E9", border="#2E7D32")
        draw_arrow(2.25, 5.8, 2.25, 4.7)

    else:
        # --- Layout without eligibility (3 stages) ---
        # IDENTIFICATION
        ax.text(0.3, 9.5, "IDENTIFICATION", fontsize=10, fontweight="bold", color="#1565C0")
        draw_box(0.5, 8.2, 3.5, 1.2,
                 f"Records identified from\ndatabases & registers\n(n = {total})\n{source_text}",
                 color="#E3F2FD", border="#1565C0")
        draw_box(5.5, 8.2, 3.5, 1.2,
                 f"Records removed before\nscreening:\nDuplicates (n = {dups})",
                 color="#FFEBEE", border="#C62828")
        draw_arrow(4.0, 8.8, 5.5, 8.8)

        # SCREENING
        ax.text(0.3, 7.5, "SCREENING", fontsize=10, fontweight="bold", color="#F57F17")
        draw_box(0.5, 5.8, 3.5, 1.2,
                 f"Records screened\n(title + abstract)\n(n = {after_dedup})",
                 color="#FFF8E1", border="#F57F17")
        draw_arrow(2.25, 8.2, 2.25, 7.0)
        draw_box(5.5, 5.8, 3.5, 1.2,
                 f"Records excluded\n(keyword rules +\nAI-assisted review)\n(n = {excluded})",
                 color="#FFEBEE", border="#C62828")
        draw_arrow(4.0, 6.4, 5.5, 6.4)

        # INCLUDED
        ax.text(0.3, 5.1, "INCLUDED", fontsize=10, fontweight="bold", color="#2E7D32")
        draw_box(0.5, 3.5, 3.5, 1.2,
                 f"Studies included\nin review\n(n = {included})",
                 color="#E8F5E9", border="#2E7D32")
        draw_arrow(2.25, 5.8, 2.25, 4.7)

    plt.tight_layout()
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close()
